tasks:
  - init: |
      echo "Gitpod init. Setting up peerjfetch dev environment."
      echo "Installing aiortc dependencies"
      apt install libavdevice-dev libavfilter-dev libopus-dev libvpx-dev pkg-config
      echo "Preparing nodejs environment"
      npm install
      npm run prepare
      npm update
      npm audit fix
    command: |
      echo "peerfetch Python dev environment:"
      cd python/peerfetch
      pyenv global system
      pip3 install -e ./src
      echo "Running the peerjfetch Python testsuite:"
      python3 -m pytest --cov=peerjs --cov-report=term tests/
      echo "To start peerjs proxy service:"
      echo "python3 -m peerjs.ext.http_proxy"
  - command: |
      echo "peerfetch JavaScript:"
      cd javascript/peerfetch
      echo "Running peerfetch JavaScript testsuite:"
      npm run test
  - command: |
      echo "Starting http server for local HTML files preview"
      npx browser-sync start -s -w      

ports:
  - port: 8080

github:
  prebuilds:
    addComment: true
    addBadge: true
