tasks:
  - init: |
      echo "Gitpod init. Setting up peerjfetch dev environment."
      echo "Installing aiortc dependencies"
      apt install libavdevice-dev libavfilter-dev libopus-dev libvpx-dev pkg-config
      echo "Preparing nodejs environment"
      cd javascript
      npm install
      npm run prepare
      npm update
      npm audit fix
    command: |
      echo "peerfetch Python dev environment:"
      cd python
      pyenv global system
      python3 -m pip install -e ./src
      echo "Running the peerjfetch Python testsuite:"
      python3 -m pytest --cov=peerfetch --cov-report=term tests/
      echo "To start peerjs proxy service:"
      echo "python3 -m peerfetch.proxy"
  - command: |
      echo "peerfetch JavaScript:"
      cd javascript
      echo "Running peerfetch JavaScript testsuite:"
      npm run test
  - init: |
      echo "Installing browser-sync..."
      npm install -g browser-sync
    command: |
      echo "Starting http server for local HTML files preview"
      cd javascript
      npx browser-sync start --watch --directory --server "../"

ports:
  - port: 8080

github:
  prebuilds:
    addComment: true
    addBadge: true
